name: Deploy API (java-api) to EC2

on:
  push:
    branches: [ "main" ]
    paths:
      - "java-api/**"
      - ".github/workflows/deploy-api.yml"

  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build API App
        working-directory: java-api
        run: mvn clean package -DskipTests

      - name: Copy API Jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "java-api/target/*.jar"
          target: "/home/ubuntu/apps/api"

      - name: Restart API Service in EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/apps/api
            rm -f app-api.jar
            mv java-api/target/*.jar app-api.jar
            sudo systemctl restart apiapp
            sudo systemctl status apiapp --no-pager
